//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Hid { get; set; }
        public decimal Price { get; set; }
        public string Address { get; set; }
        public int TypeId { get; set; }
        public int StateId { get; set; }
        public string Discription { get; set; }
        public string MaterName { get; set; }
        public string Telephone { get; set; }
    
        public virtual HouseType HouseType { get; set; }
        public virtual State State { get; set; }
    }
}
